on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:    
    - name: 📂 UPLOAD FILES
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOST_FTP }}
        username:  ${{ secrets.USER_FTP }}
        password: ${{ secrets.PASSWORD_FTP }}
        protocol: ftps
        

  

      
     

  

      
