on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v3
      - name: VERSÂO PYTHON      
        run:  python3 --version
      - name: INSTALAR
        run:  pip install -r requirements.txt     
      - name:  INSTALL PYTHON TESTE
        run: pip install pytest   
      - name: TESTANDO APP
        run: python -m pytest app.py
      - name: TESTE CONCLUIDO
        run: echo "Sucesso so concluir teste"
      # - name: BUILD TEST
      #   run: dotnet build
      # - name: TEST .NET
      #   run: dotnet test
      # - name: PIPELINE SUCCESS
      #   run: echo "PIPELINE SUCCESSFULLY!"

  

      