on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.154.56.41.29
        username: root
        password: ${{ secrets.PASSWORD_FTP }}
        

  

      
     

  

      
