on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:   
    - uses: actions/checkout@v2
    - name: 📂FILES
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.HOST_FTP }}
        username:  ${{ secrets.USER_FTP }}
        password: ${{ secrets.PASSWORD_FTP }}
        ssh_private_key: ${{ secrets.SSH_KEY }}
        sftp_only: true  
        local_path: './*'
        remote_path: '/root/ftp/'
        sftpArgs: '-o ConnectTimeout=20'
       
       
        

  

      
     

  

      
