on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:    
    - name: Upload Automático
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.154.56.41.29
        username: root
        password: '@Automate2023#'
        destination-path: ~/root

  

      
     

  

      
